# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGenfri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItemExtra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='billitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpenGenfri.Category'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OpenGenfri.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpenGenfri.Category'),
        ),
        migrations.AddField(
            model_name='billitemextra',
            name='billitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpenGenfri.BillItem'),
        ),
        migrations.AddField(
            model_name='billitemextra',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OpenGenfri.Item'),
        ),
    ]
