# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenGenfri', '0002_auto_20160514_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
